"""
YuktiFi Business Template Engine (Phase 5 & Production Specification).
Provides sector-tailored business models, default parameters, working capital days,
catchment radii, variable/fixed cost breakdowns, production models, and relevant KPIs.
"""
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional


@dataclass
class BusinessTemplate:
    category_id: str
    name: str
    sector: str
    catchment_radius_min_km: float
    catchment_radius_max_km: float
    default_inventory_days: int
    default_receivable_days: int
    default_payable_days: int
    typical_cogs_pct: float
    typical_opex_pct: float
    key_cost_drivers: List[str]
    description: str
    # --- Capital sizing parameters -------------------------------------------
    promoter_contribution_pct: float = 25.0
    annual_revenue_per_invested_rupee: float = 2.5
    typical_unit_value: float = 100.0
    depreciable_asset_share: float = 0.75
    asset_useful_life_years: float = 10.0
    # --- Operational unit defaults -------------------------------------------
    typical_selling_price: float = 20.0
    typical_variable_cost_per_unit: float = 8.0
    typical_units_per_day: float = 200.0
    typical_operating_days: int = 30
    typical_monthly_fixed_cost: float = 15000.0
    # --- Business model metadata ---------------------------------------------
    revenue_model: str = "Daily retail cash sales"
    production_model: str = "Made-to-order on premises"
    inventory_model: str = "Short-cycle fresh perishables"
    required_inputs: List[str] = field(default_factory=list)
    relevant_kpis: List[str] = field(default_factory=list)


TEMPLATES: Dict[str, BusinessTemplate] = {
    "vada_pav": BusinessTemplate(
        category_id="vada_pav",
        name="Vada Pav & Street Snacks Stall",
        sector="Food & Beverage",
        catchment_radius_min_km=0.5,
        catchment_radius_max_km=2.0,
        default_inventory_days=2,
        default_receivable_days=0,
        default_payable_days=7,
        typical_cogs_pct=40.0,
        typical_opex_pct=30.0,
        key_cost_drivers=["Potatoes, Gram Flour & Oil", "LPG Fuel & Stall Rent", "Packaging Paper"],
        description="High-frequency street snack kiosk with daily cash turnaround, short perishable inventory and zero credit sales.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=2.5,
        typical_unit_value=20.0,
        depreciable_asset_share=0.65,
        asset_useful_life_years=5.0,
        typical_selling_price=20.0,
        typical_variable_cost_per_unit=8.0,
        typical_units_per_day=250.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=18000.0,
        revenue_model="Direct consumer cash/UPI transactions per piece",
        production_model="Continuous on-demand frying and assembly",
        inventory_model="Daily raw vegetable purchase and 2-day oil/flour buffer",
        required_inputs=["Selling price per plate/piece", "Estimated plates per day", "Stall rent & electricity", "Raw materials cost"],
        relevant_kpis=["Plates Sold / Day", "Gross Margin %", "Daily Operating Cash", "Break-Even Plates"],
    ),
    "panipuri": BusinessTemplate(
        category_id="panipuri",
        name="Panipuri & Chaat Centre",
        sector="Food & Beverage",
        catchment_radius_min_km=0.5,
        catchment_radius_max_km=2.5,
        default_inventory_days=2,
        default_receivable_days=0,
        default_payable_days=7,
        typical_cogs_pct=35.0,
        typical_opex_pct=30.0,
        key_cost_drivers=["Puri Supply & Spices", "Mineral Water & Flavour Ingredients", "Counter Maintenance & Rent"],
        description="Evening footfall snack centre with rapid cash flow, minimal receivables, and strong gross profit margins.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=2.5,
        typical_unit_value=25.0,
        depreciable_asset_share=0.65,
        asset_useful_life_years=5.0,
        typical_selling_price=25.0,
        typical_variable_cost_per_unit=8.5,
        typical_units_per_day=200.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=15000.0,
        revenue_model="Direct cash and digital micro-payments",
        production_model="Batch preparation of flavoured water and customized live serving",
        inventory_model="Daily fresh ingredient procurement and dry puri stock buffer",
        required_inputs=["Price per plate", "Target plates per evening", "Kiosk rent", "Helper wage"],
        relevant_kpis=["Evening Customer Footfall", "Average Plate Ticket Size", "Contribution Margin %"],
    ),
    "retail_kirana": BusinessTemplate(
        category_id="retail_kirana",
        name="Retail Kirana / Grocery Store",
        sector="Retail",
        catchment_radius_min_km=1.0,
        catchment_radius_max_km=3.0,
        default_inventory_days=10,
        default_receivable_days=7,
        default_payable_days=14,
        typical_cogs_pct=75.0,
        typical_opex_pct=15.0,
        key_cost_drivers=["FMCG Wholesale Inventory", "Shop Rent & Electricity", "Shrinkage & Spoilage"],
        description="Essential neighborhood grocery retail store with short receivable credit cycle and regular household footfall.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=2.2,
        typical_unit_value=250.0,
        depreciable_asset_share=0.70,
        asset_useful_life_years=10.0,
        typical_selling_price=250.0,
        typical_variable_cost_per_unit=187.5,
        typical_units_per_day=60.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=25000.0,
        revenue_model="FMCG package sales & loose grains retail",
        production_model="Wholesale procurement and shelf aggregation",
        inventory_model="10-14 day revolving shelf stock with distributor credit",
        required_inputs=["Average bill value", "Daily footfall count", "Shop rent", "Distributor credit terms"],
        relevant_kpis=["Inventory Turnover Ratio", "Monthly Basket Size", "Working Capital Cycle Days"],
    ),
    "tea_stall": BusinessTemplate(
        category_id="tea_stall",
        name="Tea & Snacks Stall",
        sector="Food & Beverage",
        catchment_radius_min_km=0.5,
        catchment_radius_max_km=1.5,
        default_inventory_days=2,
        default_receivable_days=1,
        default_payable_days=7,
        typical_cogs_pct=40.0,
        typical_opex_pct=30.0,
        key_cost_drivers=["Milk & Tea Leaves", "LPG Fuel", "Stall Location Rent"],
        description="High-frequency daily cash sales business with minimal receivables.",
        promoter_contribution_pct=50.0,
        annual_revenue_per_invested_rupee=2.5,
        typical_unit_value=20.0,
        depreciable_asset_share=0.65,
        asset_useful_life_years=5.0,
        typical_selling_price=20.0,
        typical_variable_cost_per_unit=8.0,
        typical_units_per_day=200.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=15000.0,
    ),
    "dairy": BusinessTemplate(
        category_id="dairy",
        name="Dairy & Milk Collection Centre",
        sector="Dairy",
        catchment_radius_min_km=2.0,
        catchment_radius_max_km=8.0,
        default_inventory_days=1,
        default_receivable_days=10,
        default_payable_days=15,
        typical_cogs_pct=80.0,
        typical_opex_pct=12.0,
        key_cost_drivers=["Raw Milk Procurement", "Chilling Electricity", "Transport Logistics"],
        description="Perishable dairy aggregation enterprise reliant on daily collection, automated testing and cooperative supply.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=3.2,
        typical_unit_value=60.0,
        depreciable_asset_share=0.75,
        asset_useful_life_years=10.0,
        typical_selling_price=60.0,
        typical_variable_cost_per_unit=48.0,
        typical_units_per_day=300.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=22000.0,
        revenue_model="B2B bulk milk dispatch to dairies and local packet sales",
        production_model="Daily morning & evening farmer collection and bulk chilling",
        inventory_model="Daily zero-stock dispatch with 10-day settlement cycle",
        required_inputs=["Procurement rate/litre", "Selling price/litre", "Collection volume (litres/day)", "Chiller power cost"],
        relevant_kpis=["Litres Collected / Day", "FAT/SNF Recovery Margin", "Chiller Uptime"],
    ),
    "restaurant": BusinessTemplate(
        category_id="restaurant",
        name="Restaurant / Dhaba / Fast Casual Dining",
        sector="Hospitality",
        catchment_radius_min_km=3.0,
        catchment_radius_max_km=12.0,
        default_inventory_days=4,
        default_receivable_days=2,
        default_payable_days=10,
        typical_cogs_pct=45.0,
        typical_opex_pct=35.0,
        key_cost_drivers=["Rations & Fresh Perishables", "Cook & Service Staff Salaries", "Commercial Gas & Power"],
        description="Sit-down and takeaway dining establishment serving breakfast, lunch and dinner to local residents and travellers.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=3.0,
        typical_unit_value=200.0,
        depreciable_asset_share=0.75,
        asset_useful_life_years=8.0,
        typical_selling_price=200.0,
        typical_variable_cost_per_unit=90.0,
        typical_units_per_day=80.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=45000.0,
        revenue_model="Dine-in billing, counter parcel, and delivery orders",
        production_model="Commercial kitchen multi-dish preparation",
        inventory_model="Bi-weekly dry pantry and daily fresh vegetables/dairy",
        required_inputs=["Average cover spend", "Tables / seating capacity", "Kitchen staff payroll", "Premises lease"],
        relevant_kpis=["Average Revenue Per Seat (RevPASH)", "Food Cost %", "Table Turnover Rate"],
    ),
    "small_hospitality": BusinessTemplate(
        category_id="small_hospitality",
        name="Dhaba / Small Restaurant",
        sector="Hospitality",
        catchment_radius_min_km=3.0,
        catchment_radius_max_km=12.0,
        default_inventory_days=4,
        default_receivable_days=2,
        default_payable_days=10,
        typical_cogs_pct=45.0,
        typical_opex_pct=35.0,
        key_cost_drivers=["Ration & Perishables", "Cook & Service Staff", "LPG & Electricity"],
        description="Highway/town hospitality business combining quick food service with daily footfall.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=3.0,
        typical_unit_value=250.0,
        depreciable_asset_share=0.75,
        asset_useful_life_years=10.0,
        typical_selling_price=200.0,
        typical_variable_cost_per_unit=90.0,
        typical_units_per_day=80.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=45000.0,
    ),
    "bakery": BusinessTemplate(
        category_id="bakery",
        name="Bakery & Confectionery Unit",
        sector="Food Processing",
        catchment_radius_min_km=2.0,
        catchment_radius_max_km=6.0,
        default_inventory_days=6,
        default_receivable_days=5,
        default_payable_days=15,
        typical_cogs_pct=42.0,
        typical_opex_pct=30.0,
        key_cost_drivers=["Maida, Sugar, Butter & Yeast", "Oven Electricity / LPG", "Packaging Materials & Boxes"],
        description="Fresh bread, toast, biscuits and cake manufacturing unit selling through own counter and local retail supplies.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=2.8,
        typical_unit_value=120.0,
        depreciable_asset_share=0.80,
        asset_useful_life_years=8.0,
        typical_selling_price=120.0,
        typical_variable_cost_per_unit=50.0,
        typical_units_per_day=100.0,
        typical_operating_days=30,
        typical_monthly_fixed_cost=30000.0,
        revenue_model="Retail counter sales and wholesale supply to nearby tea stalls",
        production_model="Daily morning baking batches and custom cake making",
        inventory_model="Weekly flour/sugar inventory and short shelf-life fresh dispatch",
        required_inputs=["Oven capacity (kg/day)", "Average product price", "Power tariff", "Baker wages"],
        relevant_kpis=["Baking Yield %", "Wastage / Return %", "Wholesale Distribution Share"],
    ),
    "tailoring": BusinessTemplate(
        category_id="tailoring",
        name="Tailoring & Garment Works",
        sector="Service",
        catchment_radius_min_km=1.0,
        catchment_radius_max_km=5.0,
        default_inventory_days=5,
        default_receivable_days=3,
        default_payable_days=7,
        typical_cogs_pct=25.0,
        typical_opex_pct=40.0,
        key_cost_drivers=["Thread & Accessories", "Machine Maintenance", "Labor / Helper Wages"],
        description="Labor-intensive service enterprise with high profit margin and localized custom orders.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=2.5,
        typical_unit_value=1200.0,
        depreciable_asset_share=0.80,
        asset_useful_life_years=10.0,
        typical_selling_price=450.0,
        typical_variable_cost_per_unit=112.5,
        typical_units_per_day=8.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=20000.0,
        revenue_model="Piece-rate custom labor and fabric accessory markup",
        production_model="Measurement-to-delivery custom stitching",
        inventory_model="Low inventory; clients supply cloth; shop stocks trims/linings",
        required_inputs=["Stitching charges per garment", "Daily garments output", "Machine rental/EMI", "Assistant pay"],
        relevant_kpis=["Stitching Cycles Completed", "Labor Efficiency", "Seasonal Festival Surge"],
    ),
    "diagnostic": BusinessTemplate(
        category_id="diagnostic",
        name="Diagnostic & Clinical Collection Centre",
        sector="Health Service",
        catchment_radius_min_km=5.0,
        catchment_radius_max_km=15.0,
        default_inventory_days=15,
        default_receivable_days=15,
        default_payable_days=30,
        typical_cogs_pct=35.0,
        typical_opex_pct=35.0,
        key_cost_drivers=["Reagents & Testing Kits", "Calibrated Medical Devices", "Qualified Technician Salary"],
        description="Specialized healthcare service requiring wider geographical catchment and clinical accuracy.",
        promoter_contribution_pct=35.0,
        annual_revenue_per_invested_rupee=2.0,
        typical_unit_value=800.0,
        depreciable_asset_share=0.85,
        asset_useful_life_years=7.0,
        typical_selling_price=800.0,
        typical_variable_cost_per_unit=280.0,
        typical_units_per_day=15.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=40000.0,
    ),
    "service_business": BusinessTemplate(
        category_id="service_business",
        name="Service Business & Clinical Diagnostic Centre",
        sector="Health & Professional Services",
        catchment_radius_min_km=4.0,
        catchment_radius_max_km=15.0,
        default_inventory_days=15,
        default_receivable_days=15,
        default_payable_days=30,
        typical_cogs_pct=35.0,
        typical_opex_pct=35.0,
        key_cost_drivers=["Testing Kits & Diagnostic Reagents", "Lab Technician Salaries", "Equipment Calibration & Maintenance"],
        description="Clinical laboratory and sample collection centre offering pathology tests, health checkups and reports.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=2.0,
        typical_unit_value=800.0,
        depreciable_asset_share=0.85,
        asset_useful_life_years=7.0,
        typical_selling_price=800.0,
        typical_variable_cost_per_unit=280.0,
        typical_units_per_day=15.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=40000.0,
        revenue_model="Direct patient test billing and referral doctor tie-ups",
        production_model="Sample collection, analyzer batch processing, pathologist sign-off",
        inventory_model="Reagent kit refrigerated stock with 15-day replenishment",
        required_inputs=["Average test package price", "Patients/samples per day", "Technician salary", "Reagent cost per test"],
        relevant_kpis=["Daily Sample Volume", "Repeat Patient Ratio", "Gross Margin per Test"],
    ),
    "agri_machinery": BusinessTemplate(
        category_id="agri_machinery",
        name="Agricultural Machinery & Equipment Dealer / Hiring Centre",
        sector="Agriculture",
        catchment_radius_min_km=10.0,
        catchment_radius_max_km=30.0,
        default_inventory_days=30,
        default_receivable_days=20,
        default_payable_days=30,
        typical_cogs_pct=65.0,
        typical_opex_pct=20.0,
        key_cost_drivers=["Equipment Financing & Maintenance", "Diesel Fuel", "Operator Wages"],
        description="Capital-intensive agricultural service serving multiple villages across rural block/district.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=1.4,
        typical_unit_value=25000.0,
        depreciable_asset_share=0.90,
        asset_useful_life_years=10.0,
        typical_selling_price=25000.0,
        typical_variable_cost_per_unit=16250.0,
        typical_units_per_day=1.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=30000.0,
    ),
    "food_processing": BusinessTemplate(
        category_id="food_processing",
        name="Micro Food Processing (Atta Chakki / Spices Unit)",
        sector="Food Processing",
        catchment_radius_min_km=3.0,
        catchment_radius_max_km=10.0,
        default_inventory_days=12,
        default_receivable_days=7,
        default_payable_days=15,
        typical_cogs_pct=60.0,
        typical_opex_pct=20.0,
        key_cost_drivers=["Raw Grains / Spices Procurement", "3-Phase Commercial Power", "Packaging Material"],
        description="Value-addition manufacturing enterprise converting local farm produce into processed goods.",
        promoter_contribution_pct=30.0,
        annual_revenue_per_invested_rupee=2.4,
        typical_unit_value=400.0,
        depreciable_asset_share=0.80,
        asset_useful_life_years=10.0,
        typical_selling_price=400.0,
        typical_variable_cost_per_unit=240.0,
        typical_units_per_day=25.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=35000.0,
    ),
    "manufacturing": BusinessTemplate(
        category_id="manufacturing",
        name="Small Scale Manufacturing & Processing (Atta Chakki / Spices)",
        sector="Manufacturing",
        catchment_radius_min_km=3.0,
        catchment_radius_max_km=15.0,
        default_inventory_days=15,
        default_receivable_days=10,
        default_payable_days=20,
        typical_cogs_pct=60.0,
        typical_opex_pct=20.0,
        key_cost_drivers=["Raw Agro Grains / Whole Spices", "Commercial 3-Phase Power", "Packaging Pouches & Sealing"],
        description="Value-addition manufacturing enterprise converting local agricultural produce into branded packaged flour and spices.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=2.4,
        typical_unit_value=400.0,
        depreciable_asset_share=0.85,
        asset_useful_life_years=10.0,
        typical_selling_price=400.0,
        typical_variable_cost_per_unit=240.0,
        typical_units_per_day=25.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=35000.0,
        revenue_model="B2B wholesale bags and consumer retail packets",
        production_model="Milling, pulverizing, grading and pouch packaging",
        inventory_model="Bulk seasonal grain procurement with monthly rotation",
        required_inputs=["Milling machine capacity (kg/hr)", "Raw material procurement price", "Electricity tariff", "Packaging cost"],
        relevant_kpis=["Capacity Utilization %", "Milling Yield Efficiency", "Power Consumption per Kg"],
    ),
    "repair_services": BusinessTemplate(
        category_id="repair_services",
        name="Auto / Electronics Repair Works",
        sector="Repair",
        catchment_radius_min_km=2.0,
        catchment_radius_max_km=8.0,
        default_inventory_days=10,
        default_receivable_days=5,
        default_payable_days=15,
        typical_cogs_pct=40.0,
        typical_opex_pct=35.0,
        key_cost_drivers=["Spare Parts Inventory", "Specialized Tooling", "Mechanic Wages"],
        description="Service & repair enterprise combining spare part sales with technical repair labor.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=3.0,
        typical_unit_value=1500.0,
        depreciable_asset_share=0.70,
        asset_useful_life_years=7.0,
        typical_selling_price=600.0,
        typical_variable_cost_per_unit=240.0,
        typical_units_per_day=8.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=22000.0,
    ),
    "mobile_repair": BusinessTemplate(
        category_id="mobile_repair",
        name="Mobile & Electronics Repair Works",
        sector="Repair & Service",
        catchment_radius_min_km=1.5,
        catchment_radius_max_km=6.0,
        default_inventory_days=10,
        default_receivable_days=2,
        default_payable_days=14,
        typical_cogs_pct=38.0,
        typical_opex_pct=32.0,
        key_cost_drivers=["Display & IC Spare Parts", "Testing Tools & SMD Rework Station", "Technician Salary"],
        description="Smart device diagnostic, screen replacement and hardware troubleshooting shop combined with accessory retail.",
        promoter_contribution_pct=25.0,
        annual_revenue_per_invested_rupee=3.0,
        typical_unit_value=600.0,
        depreciable_asset_share=0.70,
        asset_useful_life_years=7.0,
        typical_selling_price=600.0,
        typical_variable_cost_per_unit=228.0,
        typical_units_per_day=8.0,
        typical_operating_days=26,
        typical_monthly_fixed_cost=22000.0,
        revenue_model="Diagnostic service fee, repair labor, and accessory sales",
        production_model="Walk-in turnaround service within 2-24 hours",
        inventory_model="Common screens/batteries in stock; specialized ICs ordered on demand",
        required_inputs=["Average repair charge", "Phones serviced per day", "Accessory margin %", "Shop rent"],
        relevant_kpis=["Turnaround Time", "First-Time Fix Rate", "Accessory Attachment Rate"],
    ),
}

# Aliases for flexible routing from search or legacy IDs
ALIAS_MAP: Dict[str, str] = {
    "vada_pav_stall": "vada_pav",
    "panipuri_stall": "panipuri",
    "chaat": "panipuri",
    "kirana": "retail_kirana",
    "grocery": "retail_kirana",
    "supermarket": "retail_kirana",
    "retail_shop": "retail_kirana",
    "pooja_samagri": "retail_kirana",
    "pooja_store": "retail_kirana",
    "general_store": "retail_kirana",
    "cafe": "restaurant",
    "bakery_unit": "bakery",
    "electronics_repair": "mobile_repair",
    "atta_chakki": "manufacturing",
    "flour_mill": "manufacturing",
    "tailoring": "retail_kirana",
    "dairy": "retail_kirana",
    "poultry": "retail_kirana",
    "clinical_lab": "service_business",
    "custom": "retail_kirana",
    "general": "retail_kirana",
}

DEFAULT_TEMPLATE = BusinessTemplate(
    category_id="retail_kirana",
    name="General Retail & Service Enterprise",
    sector="Retail & Shop",
    catchment_radius_min_km=1.0,
    catchment_radius_max_km=5.0,
    default_inventory_days=10,
    default_receivable_days=7,
    default_payable_days=14,
    typical_cogs_pct=60.0,
    typical_opex_pct=15.0,
    key_cost_drivers=["Inventory Stock", "Shop Rent & Utilities", "Operational Costs"],
    description="Standard enterprise model with balanced working capital and inventory cycle.",
    promoter_contribution_pct=25.0,
    annual_revenue_per_invested_rupee=2.5,
    typical_unit_value=100.0,
    depreciable_asset_share=0.70,
    asset_useful_life_years=5.0,
    typical_selling_price=100.0,
    typical_variable_cost_per_unit=60.0,
    typical_units_per_day=100.0,
    typical_operating_days=26,
    typical_monthly_fixed_cost=25000.0,
)


def get_business_template(category_id: Optional[str] = None) -> BusinessTemplate:
    """Retrieve template by canonical ID or alias, guaranteed to return a valid BusinessTemplate."""
    cid = (category_id or "").strip().lower()
    if cid and cid in TEMPLATES:
        return TEMPLATES[cid]
    mapped = ALIAS_MAP.get(cid)
    if mapped and mapped in TEMPLATES:
        return TEMPLATES[mapped]
    # Fuzzy match substring
    for key in TEMPLATES:
        if cid and (key in cid or cid in key):
            return TEMPLATES[key]
    return TEMPLATES.get("retail_kirana", DEFAULT_TEMPLATE)
